"""A synthetic stand-in for the Climate DT retrieval, for running without DestinE.

Notebooks 02-04 must be executable by anyone who clones this repo, and by CI,
neither of which has a DestinE Data Lake account. This module writes files with
exactly the schema `01_data_download.py` writes from Polytope, so the rest of
the pipeline runs unchanged.

Everything it writes is stamped `provenance = "synthetic"`, and every artefact
downstream carries that stamp forward: `03_analysis.py` records it in
`results/claim_test.json` and `04_figures.py` prints it across the figure. A
synthetic number must never be mistaken for a replication result -- the FORRT
Outcome nanopub is signed and permanent.

The generator plants a KNOWN signal: the scenario window intensifies more at
short durations than at long ones. That is deliberate. It gives
tests/test_pipeline.py something to recover, so the analysis code is tested
against a ground truth rather than against its own output. It says nothing
whatsoever about what the real Climate DT does.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

import climatedt

# Small enough to run in seconds, large enough for the pooled GEV fit to have
# something to pool.
N_CELLS = 150
N_YEARS = 6

# Planted signal: fractional intensification of the hourly rain-rate
# distribution in the scenario window, and how much of it survives averaging
# over longer durations. `SHORT_ONLY_FRACTION` of the boost applies to a single
# hour and decays with duration, which is what "short duration intensifies more"
# looks like at the level of the generator.
BASE_INTENSIFICATION = 0.10
SHORT_ONLY_FRACTION = 0.6


def _cell_coordinates(rng: np.random.Generator) -> tuple[np.ndarray, np.ndarray]:
    """Pseudo-cell centres inside Germany's bounding box."""
    lat = rng.uniform(47.3, 54.9, N_CELLS)
    lon = rng.uniform(5.9, 15.0, N_CELLS)
    return lat, lon


def _hourly_precip(
    n_hours: int, rng: np.random.Generator, intensified: bool
) -> np.ndarray:
    """Intermittent hourly precipitation in metres, shape (n_hours, N_CELLS).

    Wet hours are gamma-distributed; a slowly varying multiplicative field gives
    neighbouring hours some persistence, so a 24-hour accumulation is not just
    24 independent draws and the duration axis carries real structure.
    """
    wet = rng.random((n_hours, N_CELLS)) < 0.12
    intensity_mm = rng.gamma(shape=0.7, scale=1.6, size=(n_hours, N_CELLS))
    # Persistence: a smoothed AR(1)-ish envelope shared across cells.
    env = np.zeros(n_hours)
    for t in range(1, n_hours):
        env[t] = 0.85 * env[t - 1] + rng.normal(0.0, 1.0)
    envelope = 1.0 + 0.25 * (env - env.mean()) / (env.std() or 1.0)
    field = wet * intensity_mm * envelope[:, None]
    if intensified:
        # A burst term added to a *single* hour lifts 1-hour maxima much more
        # than 24-hour totals -- the short-duration-first signal.
        burst = rng.random((n_hours, N_CELLS)) < 0.004
        field = field * (1.0 + BASE_INTENSIFICATION * (1.0 - SHORT_ONLY_FRACTION))
        field = field + burst * rng.gamma(2.0, 6.0, (n_hours, N_CELLS)) * SHORT_ONLY_FRACTION
    return np.clip(field, 0.0, None) / 1000.0  # mm -> m, as the Climate DT delivers


def write_window(raw_dir: Path, window: str, seed: int) -> list[Path]:
    """Write N_YEARS of synthetic hourly files for one window."""
    spec = climatedt.WINDOWS[window]
    first = spec["years"][0]
    rng = np.random.default_rng(seed)
    lat, lon = _cell_coordinates(rng)
    written = []
    for offset in range(N_YEARS):
        year = first + offset
        time = pd.date_range(f"{year}-01-01", f"{year}-12-31 23:00", freq="h")
        values = _hourly_precip(len(time), rng, intensified=(window != "hist"))
        ds = xr.Dataset(
            {"tp": (("time", "cell"), values.astype("float32"))},
            coords={
                "time": time,
                "cell": np.arange(N_CELLS, dtype="int32"),
                "latitude": ("cell", lat),
                "longitude": ("cell", lon),
            },
            attrs={
                "provenance": "synthetic",
                "window": window,
                "window_label": spec["label"],
                "year": year,
                "units_note": "tp in metres per hour, matching the Climate DT clte stream",
                "warning": (
                    "SYNTHETIC DATA generated by scripts/synthetic_climatedt.py. "
                    "Not Destination Earth output. Any number derived from it is a "
                    "smoke test, never a replication result."
                ),
                "request": json.dumps({"synthetic": True, "seed": seed, "year": year}),
            },
        )
        ds["tp"].attrs.update(units="m", long_name="Total precipitation (hourly accumulation)")
        out = raw_dir / f"tp_{window}_{year}.nc"
        out.parent.mkdir(parents=True, exist_ok=True)
        ds.to_netcdf(out)
        written.append(out)
    return written


def write_warming_levels(raw_dir: Path) -> Path:
    """A stand-in for the global-mean temperature of each window, in kelvin."""
    doc = {
        "provenance": "synthetic",
        "gmst_k": {"hist": 287.0, "ssp370": 288.5},
        "note": "Synthetic placeholder; the real value comes from the clmn avg_2t fields.",
    }
    out = raw_dir / "warming_levels.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        json.dump(doc, f, indent=2)
    return out


def write_all(raw_dir: Path, seed: int = 20260906) -> list[Path]:
    """Write every synthetic input the rest of the pipeline expects."""
    paths: list[Path] = []
    for i, window in enumerate(climatedt.WINDOWS):
        paths += write_window(raw_dir, window, seed=seed + i)
    paths.append(write_warming_levels(raw_dir))
    return paths


if __name__ == "__main__":
    import sys

    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("data/raw")
    for p in write_all(target):
        print(f"  wrote {p}")
